name: CI

on: 
  push:
    branches:    
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yaml
        environment-name: electric
        condarc: |
            channels:
              - conda-forge
              - defaults
        create-args: >- 
          python=3.11

    - name: Build dependencies
      shell: bash -l {0}
      run: |
        pip install pytest
        pip install pytest-cov

    - name: Build ELECTRIC with Tinker
      shell: bash -l {0}
      run: |
        ./build.sh

    - name: Run the pytest tests
      env:
        CODECOV_TOKEN: "8b90eeee-10a0-46aa-be29-f2680364ea1a"
      shell: bash -l {0}
      run: |
        # Run pytest
        cd ELECTRIC/pytest
        pytest -vv --cov-report=xml --cov=ELECTRIC --cov=util
        ls -a -l
        bash <(curl -s https://codecov.io/bash)
